import type { Metadata } from "next";
import { Bebas_Neue, Instrument_Serif, Roboto_Condensed } from "next/font/google";
import "./globals.css";



const bebasNeue = Bebas_Neue({
  variable: "--font-main",
  subsets: ["latin"],
  weight: ["400"],
});
const instrumentSerif = Instrument_Serif({
  variable: "--font-secondary",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Ron Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` text-black ${instrumentSerif.variable}  ${bebasNeue.variable}   antialiased`}>{children}</body>
    </html>
  );
}
